// Licensed to ObjectStyle LLC under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ObjectStyle LLC licenses
// this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

== Overview

=== What is Bootique

Bootique is a platform for building container-less runnable Java applications. It is an ideal technology for
microservices, as it allows you to create a fully-functional app with minimal-to-no setup. Though it is
not limited to a specific kind of application (or to the "micro" size) and can be used for REST services, webapps,
runnable jobs, DB migrations, JavaFX GUI apps or really anything else.

Unlike traditional container-based apps, Bootique allows you to control your `main()` method and create Java apps that
behave like simple executable commands:

[source,bash]
----
java -jar my.jar [arguments]
----

Each Bootique app can be started with a YAML configuration, or configured with shell variables and is ideally suited
for Docker / cloud deployments.

Compared to other products in this space Bootique has a focus on modularity and clean pluggable architecture.
It is built on top of a dependency injection container, and pretty much anything in Bootique can be customized/overridden
to your liking.

=== Java Version

Java 8 or newer is required.

=== Build System

Bootique apps can be built using any Java build system (Ant, Maven, Gradle, etc). Examples in the documentation are
based on Maven.
