// Licensed to ObjectStyle LLC under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ObjectStyle LLC licenses
// this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

== Programming

A "main" class in a Bootique application might look like this:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/Application.java[tag=Application]
----

<1> `Bootique` class is the "builder" of our app that allows to configure it before startup
<2> Enables <<modules_loading,module auto-loading>>
<3> Creates a `BQRuntime` object
<4> Executes the runtime `run()` method. The outcome depends on what options were passed to the app on the command line
<5> Exits the app passing the exit code to the OS

Actually, there is a shorter version of `main(..)` that's what you'd normally do in a real app that combines creation
and execution in a single call to `exec()`:
[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/Application1.java[tag=Application]
----
But let's explore the `BQRuntime` object. It represents the entry point of the application, holding all objects
(aka "services") that were created by the `Bootique` builder. For all
intents and purposes, `BQRuntime` _is_ the "application". You can peek inside the runtime to access its objects. E.g.,
here we are retrieving a `Cli` instance that is defined in Bootique and describes the command line arguments
our app was started with:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/Runtime.java[tag=getInstance]
----

What objects exist in the runtime and how they are initialized is determined by what "modules" `Bootique` discovered
and loaded, so next let's discuss what modules are.

=== Modules
A module is a class that implements `BQModule`. Modules serve as "blueprints" for Bootique to create application objects
via a combination of Bootique "bindings" API and _dependency injection_ (DI).

NOTE: Colloquially, the term "modules" is also applied to `.jar` files that contain those classes together with a
bunch of "regular" classes. So we will use the word interchangeably to refer to either a specific java class implementing
`BQModule` or the whole `.jar` that contains such a class.

Here are two examples of the Bootique standard modules:

* `bootique-jetty` that integrates Jetty server into your application
* `bootique-jdbc` that allows to work with relational databases, and so on.

It is helpful for you to think of your own code as being "organized into modules" as well. An example of a simple
custom module is shown below with an example of an object binding API that will be discussed later:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/modules/MyModule.java[tags=MyModule]
----

NOTE: By convention, all classes logically belonging to a module are packaged in a separate `.jar`, though nothing
prevents you from keeping multiple BQModules in a single `.jar`, or spreading the module code across multiple jars.
Other than autoloading descriptors explained below, there are no special packaging requirements for modules. When they
are combined in runtime, it is all a single classpath.

NOTE: Java Platform Module System (JPMS) is conceptually close to Bootique modules, and we would love to fully align the
two. Unfortunately, it is our experience that forcing the users to adhere to JPMS everywhere would result in lots of
limitations and invariable productivity loss, so we are intentionally ignoring possible JPMS synergies.

[#modules_loading]
==== Modules (Auto) Loading

When a Bootique app is started, it loads object definitions from all modules it is aware of. Those can come from two
places:

* Modules explicitly added to Bootique: `Bootique.app(args).module(MyModule.class)`
* "Auto-loadable" modules

The first category is self-explanatory and allows to manually specify which modules should be in the app:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/Modules.java[tags=explicitModules]
----

<1> Adding a module by `BQModule` type
<2> Adding a module as a lambda

The second category is modules that will be discovered automatically by looking for
`META-INF/services/io.bootique.BQModule` files on the classpath, and getting the names of modules from those files:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/Modules.java[tags=autoLoadableModules]
----

<1> Module auto-loading needs to be turned on explicitly
<2> Auto-loading can be combined with explicit modules

In this example, instead of adding `JettyModule` explicitly, we turned on auto-loading allowing Bootique to locate and
load this standard module (assuming it was added to the application as a dependency). When writing your own auto-loadable
modules, you would add a line to `META-INF/services/io.bootique.BQModule`, containing the fully-qualified name of the
BQModule Java class. E.g.:

[source,text]
----
com.foo.MyModule
----

If you have more than one module in a given project, you should put all the names in this file, one per line. The result
of autoloading, is that you can manage inclusion/exclusion of modules purely via the build system instead of in
the code. Auto-loading is the recommended mechanism for assembling your app in almost all cases. All the standard
Bootique modules are autoloadable.

If all your code is packaged in auto-loadable modules, you may not even need a custom main class.
`io.bootique.Bootique` class itself declares a `main()` method and can be used as an app launcher.
This creates some interesting possibilities. E.g. you can create Java projects that have no code of their own and are
simply collections of modules declared as compile dependencies.

==== Modules Metadata

`BQModule` has a method called `crate()` that you can optionally implement to expose module metadata to Bootique:
[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming//modules/MyModuleWithCrate.java[tags=MyModuleWithCrate]
----
The returned "crate" can contain information about module configuration structure, its deprecation status, etc.
While you can write modules without explicit "crates", providing a "crate" with as much information about the module
as possible, would help Bootique to help your users (and your future self) to understand what the module does, and how
to use it.

==== Deprecating Modules

TODO

=== Defining Application Objects

As mentioned above, modules are object assembly blueprints. When implementing a module, you write Java code that
defines how your objects should be created and initialized when the app is started. This is done via bindings and
provider methods, and with the assistance of the dependency injection (DI) mechanism built into Bootique.

==== Dependency Injection

Let's start with how you can leverage DI when creating your objects. Objects can annotate their fields and/or
constructors with `@Inject` to indicate which internal variables they want
to be provided ("injected") by the Bootique DI environment. To demonstrate this, we will show a couple of
implementations of a simple "hello" service that returns a greeting:
[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/injection/Hello.java[tags=hello]
----
An implementation of this service would need another service called `UserNameService` that returns a user name and
needs to be injected. Here is a field injection flavor:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/injection/HelloService1.java[tags=fieldInjection]
----
And here is a constructor flavor:
[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/injection/HelloService2.java[tags=constructorInjection]
----
Both flavors are identical in terms of functionality. Constructor variety is more verbose, but arguably results in a
cleaner API, as the object can be created if needed without a DI environment.

==== Bindings

Regardless of which flavor was selected,
the implementation needs to be _bound_ in the module class:
[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/injection/HelloModule1.java[tags=binding]
----
This creates a permanent association between `Hello` interface and a specific implementation. `Hello` can now be injected
into other services. A single instance of `HelloService2` is created automatically by the DI container, with a real
object transparently provided for the "nameService".

If the service construction requires additional logic, instead of binding service implementation, you can create and
bind a Java class that implements `Provider<Service>`. E.g.:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/injection/HelloService3Provider.java[tags=provider]
----
[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/injection/HelloModule2.java[tags=binding]
----
Provider class has the same rules for injection of its own dependencies as regular objects (either annotated fields or
annotated constructor). The benefit of the provider is that it can implement custom assembly logic, which is separate from
the service itself. It also allows the service it creates to be completely free from injection annotations. Still
creating a provider class may be an overkill, and there is a simpler way to define small bits of assembly code -
"provider methods" discussed next.

==== Provider Module Methods

Any method of a module class annotated with `@Provides` is treated as an object declaration. E.g.:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/injection/HelloModule3.java[tags=binding]
----
<1> Provider method that does both assembly and binding of the Hello service.
<2> `configure(..)` method can be empty, as the service was already bound via `provideHello`. Of course, it can also contain
bindings for unrelated services.

What makes `provideHello` method a "provider" is the `@Provides` annotation. The access modifier
is irrelevant (can be "public", "protected", etc.). The method does both assembly and binding of
the "Hello" service. The return type (`Hello`) is used as the binding key. And while there is no `@Inject` annotation
in use anywhere, injection in fact also happens here - all method arguments ("nameService" in this case) are injected
by the DI environment.

==== Injection in Collections
TODO

==== Injection and Generics
TODO

=== Configuration and Configurable Factories

Bootique Modules obtain their configuration in a form of "factory objects". We'll show some examples shortly.
For now let's focus on the big picture, namely the fact that Bootique app configuration is multi-layered and
roughly follows the sequence of "code - config files (contributed) - config files (CLI) - overrides".
"Code" is the default values that are provided in constructors of factory objects. Config files overlay those defaults with their own values.
Config files can be either contributed in the code, or specified on the command line. Files is where the bulk of configuration usually stored.
Finally, config values may be further overridden via Java properties and/or environment variables.

==== Configuration via YAML Files

Format of configuration file can be either JSON or YAML. For simplicity, we'll focus on YAML format, but the two are interchangeable.
Here is an example config file:

[source,yaml]
----
log:
  level: warn
  appenders:
    - type: file
      logFormat: '%c{20}: %m%n'
      file: target/logback/debug.log

jetty:
  context: /myapp
  connectors:
    - port: 12009
----

While not strictly required, as a rule the top-level keys in the file belong to configuration objects of individual modules.
In the example above "log" subtree configures `bootique-logback` module, while "jetty" subtree configures `bootique-jetty`.
For standard modules refer to module-specific documentation on the structure of the supported configuration
(or run your app `-H` flag to print supported config to the console). Here we'll discuss how to build your own configuration-aware module.

Bootique allows each Module to read its specific configuration subtree as an object of the type defined in the Module.
Very often such an object is written as a factory that contains a bunch of setters for configuration properties,
and a factory method to produce some "service" a Module is interested in. Here is an example factory:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/configuration/yaml/MyFactory.java[tag=MyFactory]
----

The factory contains configuration property declarations, as well as public setters for these properties. (You may
create getters as well. It is not required, but may be useful for unit tests, etc.). Now let's take a look at the
Module class:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/configuration/yaml/MyModule.java[tag=MyModuleConfig]
----

A sample configuration that will work with our module may look like this:

[source,yaml]
----
my:
  intProperty: 55
  stringProperty: 'Hello, world!'
----

A few points to note here:

* Subclassing from `BaseModule` provides a few utilities, such as a shorter "config" method and a default configuration
key ("my" in this case. See the next bullet).
* Calling our module "MyModule" and extending from `BaseModule` gives it access to the protected "configPrefix"
property that is initialized to the value of "my" based on the module class name. The naming convention here is to use
the Module simple class name without the "Module" suffix and converted to lowercase.
* `@Provides` annotation is a Bootique DI way of marking a `BQModule` method as a "provider" for a certain type of injectable
service. All its parameters are themselves injectable objects.
* `ConfigurationFactory` is the class used to bind a subtree of the app YAML configuration to a given Java object
(in our case - MyFactory). The structure of MyFactory is very simple here, but it can be as complex as needed,
containing nested objects, arrays, maps, etc. Internally Bootique uses
https://github.com/FasterXML/jackson[Jackson framework] to bind YAML to a Java class, so all the features of Jackson
can be used to craft configuration.

==== Configuration File Loading

A config file can be passed to a Bootique app via DI (those are usually coming from classpath) or on the command line:

* Contributing a config file via DI:
+
[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/configuration/fileLoading/MyModule.java[tag=MyModuleExtendBinder]
----
+
A primary motivation for this style is to provide application default configuration, with YAML files often embedded in
the app and read from the classpath (as suggested by the "classpath:.." URL in the example). More than one configuration
can be contributed. E.g. individual modules might load their own defaults. Multiple configs are combined in a single
config tree by the runtime. The order in which this combination happens is undefined, so make sure there are no conflicts
between them. If there are, consider replacing multiple conflicting configs with a single config.

* Conditionally contributing a config file via DI. It is possible to make DI configuration inclusion conditional on the
presence of a certain command line option:
+
[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/configuration/fileLoading/MyModule.java[tag=MyModuleQAOption]
----

* Specifying a config file on the command line. Each Bootique app supports `--config` option that takes a configuration
file as parameter. To specify more than one file, use `--config` option multiple times. Configurations will be loaded
and merged together in the order of their appearance on the command line.

* Specifying a single config value via a custom option:
+
[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/configuration/fileLoading/MyModule.java[tag=MyModuleDBOption]
----
+
This adds a new `--db` option to the app that can be used to set JDBC URL of a datasource called "mydb". If value is
not specified, the default one will be used.

==== Configuration via Properties

YAML file can be thought of as a set of nested properties. E.g. the following config

[source,yaml]
----
my:
  prop1: val1
  prop2: val2
----

can be represented as two properties ("my.prop1", "my.prop2") being assigned some values.
Bootique takes advantage of this structural equivalence and allows defining configuration via properties as an alternative
(or more frequently - an addition) to YAML.
If the same "key" is defined in both YAML file and a property, `ConfigurationFactory` would use the value of the property
(in other words properties override YAML values).

To turn a given property into a configuration property, you need to prefix it with "`bq.`".
This "namespace" makes configuration explicit and helps to avoid random naming conflicts with properties otherwise present in the system.

Properties can be provided to Bootique via BQCoreModule extender:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/configuration/properties/MyModule.java[tag=MyModule]
----

Alternatively they can be loaded from system properties. E.g.:

[source,bash]
----
java -Dbq.my.prop1=valX -Dbq.my.prop2=valY -jar myapp.jar
----

Though generally this approach is sneered upon, as the authors of Bootique are striving to make Java apps look minimally "weird" in deployment,
and "-D" is one of those unintuitive "Java-only" things. Often a better alternative is to define the bulk of configuration in YAML,
and pass values for a few environment-specific properties via shell variables (see the next section) or bind them to CLI flags.

==== Configuration via Environment Variables

Bootique allows to use _environment variables_ to specify/override configuration values. While variables work similar to JVM properties,
using them has advantages in certain situations:

* They may be used to configure credentials, as unlike YAML they won't end up in version control, and unlike Java properties,
they won't be visible in the process list.
* They provide customized application environment without changing the launch script and are ideal for containerized and other virtual environments.
* They are more user-friendly and appear in the app help.

To declare variables associated with configuration values, use the following API
(notice that no "bq." prefix is necessary here to identify the configuration value):

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/configuration/environment/MyModule.java[tag=MyModule]
----

So now a person running the app may set the above configuration as

[source,bash]
----
export P1=valX
export P2=valY
----

Moreover, explicitly declared vars will automatically appear in the application help, assisting the admins in configuring your app

_(TODO: document BQConfig and BQConfigProperty config factory annotations required for the help generation to work)_

[source,bash]
----
$ java -jar myapp-1.0.jar --help
...
ENVIRONMENT
      P1
           Sets value of some property.

      P2
           Sets value of some other property.
----

==== Polymorphic Configuration Objects

A powerful feature of Jackson is the ability to dynamically create subclasses of the configuration objects.
Bootique takes full advantage of this. E.g. imagine a logging module that needs "appenders" to output its log messages
(file appender, console appender, syslog appender, etc.).
The framework might not be aware of all possible appenders its users might come up with in the future.
Yet it still wants to have the ability to instantiate any of them, based solely on the data coming from YAML.
Moreover, each appender will have its own set of incompatible configuration properties.
In fact this is exactly the situation with `bootique-logback` module.

Here is how you ensure that such a polymorphic configuration is possible. Let's start with a simple class hierarchy:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/configuration/polymorphic/BaseType.java[tag=polymorphic]
include::../../../../test/java/io/bootique/docs/programming/configuration/polymorphic/ConcreteType1.java[tag=polymorphic]
include::../../../../test/java/io/bootique/docs/programming/configuration/polymorphic/ConcreteType2.java[tag=polymorphic]
----

Now let's create a matching set of factories to create one of the concrete subtypes of `BaseType`. Let's use Jackson annotations to link
specific types of symbolic names to be used in YAML below:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/configuration/polymorphic/factory/BaseTypeFactory.java[tag=polymorphic]
include::../../../../test/java/io/bootique/docs/programming/configuration/polymorphic/factory/ConcreteTypeFactory1.java[tag=polymorphic]
include::../../../../test/java/io/bootique/docs/programming/configuration/polymorphic/factory/ConcreteTypeFactory2.java[tag=polymorphic]
----

After that we need to create a service provider file called `META-INF/service/io.bootique.config.PolymorphicConfiguration`
where all the types participating in the hierarchy are listed (including the supertype):

[source,text]
----
com.foo.BaseTypeFactory
com.foo.ConcreteTypeFactory1
com.foo.ConcreteTypeFactory2
----

This should be enough to work with configuration like this:

[source,yaml]
----
my:
  type: type2
  someVar: someVal
----

The service of `BaseType` is bound in Bootique DI using the standard `ConfigurationFactory` approach described above.
Depending on the YAML config, one of the subclasses of `BaseType` will be created:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/configuration/polymorphic/factory/BaseTypeFactory.java[tag=polymorphicProvides]
----

If another module decides to create yet another subclass of BaseType, it will need to create its own
`META-INF/service/io.bootique.config.PolymorphicConfiguration` file and add a new factory name there.

=== Using Modules

Modules often depend on other "upstream" modules. They can interact with upstream modules in a few ways:

* Use upstream services - inject objects defined in an upstream module in this module objects
* Contribute extensions - inject module's objects to collections and maps from the upstream module, thus extending
upstream module behavior.

Let's use https://github.com/bootique/bootique/blob/master/bootique/src/main/java/io/bootique/BQCoreModule.java[BQCoreModule]
as an example of an upstream module, as it is available in all apps.

==== Injecting Other Module's Services

You can inject any services declared in other modules. E.g. `BQCoreModule` defines an array of CLI arguments passed to
the `main()` method, that can be injected in our module:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/modules/using/MyService.java[tag=MyService]
----

<1> Since there can potentially be more than one `String[]` in a DI container, Bootique `@Args` annotation is used to
disambiguate the array that we are referring to.

==== Contributing to Other Modules

// need to use an attribute for link due to special chars not parsable by asciidoc
:link-todi-with-underscores: https://bootique.io/docs/{bootique_doc_version}/bootique-di-docs/#_collections

Bootique DI supports {link-todi-with-underscores}[Collection bindings],
intended to _contribute_ objects defined in a downstream module to collections/maps used by services in upstream modules.
Bootique hides DI API complexities, usually providing "extenders" in each module. E.g. the following code adds
`MyCommand` the app set of commands:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/modules/using/MyModule.java[tag=MyModule]
----

Here we obtained an extender instance via a static method on BQCoreModule.
Most standard modules define their own extenders accessible via `&quot;extend(Binder)&quot;`.
This is a pattern you might want to follow in your own modules.

=== Commands

Bootique runtime contains a set of commands coming from Bootique core and from all the modules currently in effect in the app.
On startup Bootique attempts to map command-line arguments to a single command type.
If no match is found, a _default_ command is executed (which is normally a "help" command). To list all available commands,
the app can be run with `--help` option (in most cases running without any options will have the same effect). E.g.:

[source,bash]
----
$ java -jar myapp-1.0.jar --help

NAME
      com.foo.MyApp

OPTIONS
      -c yaml_location, --config=yaml_location
           Specifies YAML config location, which can be a file path or a URL.

      -h, --help
           Prints this message.

      -H, --help-config
           Prints information about application modules and their configuration
           options.

      -s, --server
           Starts Jetty server.

----

==== Writing Commands

Most common commands are already available in various standard modules, still often you'd need to write your own.
To do that, first create a command class. It should implement `io.bootique.command.Command` interface,
though usually it more practical to extend `io.bootique.command.CommandWithMetadata` and provide some metadata used in help and elsewhere:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/commands/writing/MyCommand.java[tag=Commands]
----

The command initializes metadata in constructor and implements the "run" method to run its code.
The return CommandOutcome object instructs Bootique what to do when the command finishes.
The object contains desired system exit code, and exceptions that occurred during execution.
To make the new command available to Bootique, add it to `BQCoreModule`'s extender, as was already shown above:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/commands/writing/MyModule.java[tag=Commands]
----

To implement a "daemon" command running forever until it receives an OS signal (e.g. a web server waiting for user requests) , do something like this:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/commands/writing/MyCommand.java[tag=CommandsRun]
----

==== Injection in Commands

Commands can inject services, just like most other classes in Bootique. There are some specifics though.
Since commands are sometimes instantiated, but not executed (e.g. when `--help` is run that lists all commands),
it is often desirable to avoid immediate instantiation of all dependencies of a given command.
So a common pattern with commands is to inject `javax.inject.Provider` instead of direct dependency:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/commands/injection/MyCommand.java[tag=Commands]
----

==== Decorating Commands

Each command typically does a single well-defined thing, such as starting a web server, executing a job, etc.
But very often in addition to that main thing you need to do other things. E.g. when a web server is started, you might also want to run a few more commands:

* Before starting the server, run a health check to verify that any external services the app might depend upon are alive.
* Start a job scheduler in the background.
* Start a monitoring "heartbeat" thread.

To run all these "secondary" commands when the main command is invoked, Bootique provides command decorator API.
First you create a decorator policy object that specifies one or more secondary commands and their invocation strategy (either _before_ the main command,
or _in parallel_ with it). Second you "decorate" the main command with that policy:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/commands/decorating/MyCommand.java[tag=Commands]
----

Based on the specified policy Bootique figures out the sequence of execution and runs the main and the secondary commands.

=== Options

==== Simple Options

In addition to commands, the app can define "options". Options are not associated with any runnable java code,
and simply pass command-line values to commands and services. E.g. the standard "`--config`" option is used to locate
configuration file(s). Unrecognized options cause application startup errors. To be recognized, options need to be
"contributed" to Bootique similar to commands:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/options/MyOption.java[tag=Options]
----

To read a value of the option, a service should inject `io.bootique.cli.Cli` object (commands also get this object as a parameter to "run") :

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/options/MyOption.java[tag=OptionsInject]
----

==== Configuration Options

While you can process your own options as described above, options often are just aliases to enable certain pieces of configuration.
Bootique supports three flavors of associating options with configuration. Let's demonstrate them here.

. Option value sets a config property:
+
[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/options/configuration/MyOption.java[tag=OptionsConfig]
----
. Option presence sets a property to a predefined value:
+
[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/options/configuration/MyOption.java[tag=OptionsPredefined]
----
. Option presence loads a config resource, such as a YAML file:
+
[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/options/configuration/MyOption.java[tag=OptionsYaml]
----

The order of config-bound options on the command line is significant, just as the order of "`--config`" parameters.
Bootique merges configuration associated with options from left to right, overriding any preceding configuration if there is an overlap.

=== Logging

==== Loggers in the Code

Standard Bootique modules use https://www.slf4j.org/[SLF4J] internally, as it is the most convenient least common denominator framework,
and can be easily bridged to other logging implementations. Your apps or modules are not required to use SLF4J, though if they do,
it will likely reduce the amount of bridging needed to route all logs to a single destination.

==== Configurable Logging with Logback

For better control over logging a standard module called `bootique-logback` is available, that integrates https://logback.qos.ch/[Logback framework] in the app. It seamlessly bridges SLF4J (so you keep using SLF4J in the code), and allows to configure logging via YAML config file, including appenders (file, console, etc.) and per class/package log levels. Just like any other module, `bootique-logback` can be enabled by simply adding it to the pom.xml dependencies, assuming `autoLoadModules()` is in effect:

.Maven
[%collapsible%open]
====
[source,xml]
----
<dependency>
    <groupId>io.bootique.logback</groupId>
    <artifactId>bootique-logback</artifactId>
</dependency>
----
====

.Gradle
[%collapsible]
====
[source,groovy]
----
{
  implementation: 'io.bootique.logback:bootique-logback'
}
----
====

See `bootique-logback` module https://bootique.io/docs/{bootique_doc_version}/bootique-logback-docs/[documentation] for further details.

==== BootLogger

To perform logging during startup, before DI environment is available and YAML configuration is processed,
Bootique uses a special service called `BootLogger`, that is not dependent on SLF4J and is not automatically bridged to Logback.
It provides an abstraction for writing to stdout / stderr, as well as conditional "trace" logs sent to stderr.
To enable Bootique trace logs, start the app with `-Dbq.trace` as described in the deployment section.

BootLogger is injectable, in case your own code needs to use it. If the default BootLogger behavior is not satisfactory,
it can be overridden right in the `main(..)` method, as unlike other services, you may need to change it before DI is available:

[source,java,indent=0]
----
include::../../../../test/java/io/bootique/docs/programming/logging/Application.java[tag=Logging]
----
