// Licensed to ObjectStyle LLC under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ObjectStyle LLC licenses
// this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

== Assembly and Deployment

This chapter discusses how to package Bootique apps for deployment/distribution and how to run them. We are going to
present two approaches that produce cross-platform runnable applications -
"<<runnable-jar-with-dependencies,Runnable Jar with Dependencies>>" and
"<<runnable-jar-with-lib,Runnable Jar with "lib" Folder>>". They only differ in how dependencies are packaged and
referenced.

Ultimately any Bootique app is just a Java app with the `main(..)` method and hence can be executed
using `java` command. With that understanding you can come up with your own custom packaging strategies.

[#runnable-jar-with-dependencies]
=== Runnable Jar with Dependencies

Under this approach application classes, resources and all classes and resources from dependency jars are packaged in
a single "fat" runnable jar. In Maven this can be accomplished with `maven-shade-plugin`:
[source,xml]
----
<build>
    <pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <configuration>
                    <createDependencyReducedPom>true</createDependencyReducedPom>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>${main.class}</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </pluginManagement>
    <plugins>
        <plugin>
            <artifactId>maven-shade-plugin</artifactId>
        </plugin>
    </plugins>
</build>
----
Make sure you set the `main.class` property in the POM to the appropriate class value from your application or to
`io.bootique.Bootique`:
[source,xml]
----
<properties>
    <main.class>com.foo.Application</main.class>
</properties>
----
Once the pom is configured, you can assemble and run the jar. E.g.:

[source,bash]
----
mvn clean package
java -jar target/myapp-1.0.jar
----

[#runnable-jar-with-lib]
=== Runnable Jar with "lib" Folder

"Jar-with-dependencies" packaging described above is extremely convenient. It produces a single file that is easy to move
around and execute. It is not without downsides though:

* It is incompatible with Java Platform Module System (JPMS). Java allows only one `module-info.class` file per `.jar`.
So if your app or its dependencies contain one or more of those module descriptors, `maven-shade-plugin` won't be
able to package them properly.
* It is incompatible with https://openjdk.java.net/jeps/238[multi-release jar files]. Actually there's no technical
reason why `maven-shade-plugin` can't repackage such jars correctly, but as of this writing (plugin version 3.2.1) it
doesn't, losing Java version-specific code.

An alternative way of packaging that does not have these limitations is a folder with a runnable application
jar at the root level and all dependency jars in the `lib/` folder next to it:
```
my-app-1.0/
    # Runnable jar with classpath in MANIFEST.MF referencing "lib/*"
    my-app-1.0.jar
    # Dependencies folder
    lib/
        bootique-X.X.jar
        slf4j-api-1.7.25.jar
        ...
```
This folder is usually archived into a single `.tar.gz` or `.zip` file. It would then be unpacked on the
machine where the application needs to run.

Creating such packaging with Maven involves `maven-jar-plugin`, `maven-dependency-plugin` and `maven-assembly-plugin`.
First let's create the folder structure:
[source,xml]
----
<properties>
    <main.class>com.foo.Application</main.class>
</properties>
...
<build>
    <plugins>
        <plugin>
            <artifactId>maven-jar-plugin</artifactId>
            <configuration>
                <archive>
                    <manifest>
                        <mainClass>${main.class}</mainClass>
                        <addClasspath>true</addClasspath>
                        <classpathPrefix>lib/</classpathPrefix>
                        <useUniqueVersions>false</useUniqueVersions>
                    </manifest>
                </archive>
            </configuration>
        </plugin>
        <plugin>
            <artifactId>maven-dependency-plugin</artifactId>
            <configuration>
                <includeScope>runtime</includeScope>
                <outputDirectory>${project.build.directory}/lib</outputDirectory>
            </configuration>
            <executions>
                <execution>
                    <id>assembly</id>
                    <phase>prepare-package</phase>
                    <goals>
                        <goal>copy-dependencies</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
----

The above configuration places both main jar and "lib/" folder under `target/`, so you can build and run the app like this:
[source,bash]
----
$ mvn clean package
$ java -jar target/myapp-1.0.jar
----
To prepare the app for distribution as a single archive, you will need to add an assembly step. Start by creating an
`assembly.xml` descriptor file:
[source,xml]
----
<assembly xmlns="http://maven.apache.org/ASSEMBLY/2.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/ASSEMBLY/2.0.0 https://maven.apache.org/xsd/assembly-2.0.0.xsd">
    <id>tar.gz</id>
    <formats>
        <format>tar.gz</format>
    </formats>
    <fileSets>
        <fileSet>
            <directory>${project.build.directory}</directory>
            <useDefaultExcludes>true</useDefaultExcludes>
            <outputDirectory>./</outputDirectory>
            <includes>
                <include>${project.artifactId}-${project.version}.jar</include>
                <include>lib/</include>
            </includes>
        </fileSet>
    </fileSets>
</assembly>
----
Now configure `maven-assembly-plugin`:
[source,xml]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-assembly-plugin</artifactId>
    <version>3.1.1</version>
    <configuration>
        <appendAssemblyId>false</appendAssemblyId>
        <descriptors>
            <descriptor>assembly.xml</descriptor>
        </descriptors>
        <tarLongFileMode>posix</tarLongFileMode>
    </configuration>
     <executions>
        <execution>
            <id>assembly</id>
            <phase>package</phase>
            <goals>
                <goal>single</goal>
            </goals>
        </execution>
    </executions>
</plugin>
----
After you rerun packaging again, you should see `my-app-1.0.tar.gz` file in the `target` folder. This file can be
sent to the end users or copied to your servers and unpacked there:
[source,bash]
----
$ mvn clean package
$ ls target/*.tar.gz

my-app-1.0.tar.gz
----

NOTE: An extra benefit of such packaging is that you can include any additional files with your application distro,
such as installation instructions, custom startup scripts, licenses, etc. All of this is configured in `assembly.xml`.

=== Tracing Bootique Startup

To see what modules are loaded, to view full app configuration tree and to trace other events that happen on startup, run your app with `-Dbq.trace` option. E.g.:

[source,bash]
----
$ java -Dbq.trace -jar target/myapp-1.0.jar --server
----

You may see an output like this:

[source,text]
----
Skipping module 'JerseyModule' provided by 'JerseyModuleProvider' (already provided by 'Bootique')...
Adding module 'BQCoreModule' provided by 'Bootique'...
Adding module 'JerseyModule' provided by 'Bootique'...
Adding module 'JettyModule' provided by 'JettyModuleProvider'...
Adding module 'LogbackModule' provided by 'LogbackModuleProvider'...
Merged configuration: {"log":{"logFormat":"[%d{\"dd/MMM/yyyy:HH:mm:ss,SSS\"}]
%t %p %X{txid:-?} %X{principal:-?} %c{1}: %m%n%ex"},"trace":""}
----

WARNING: Printing configuration may expose sensitive information, like database passwords, etc. Make sure you use
`-Dbq.trace` for debugging only and don't leave it on permanently in a deployment environment.
