package io.bootique;

import com.google.inject.Module;

import java.lang.reflect.Type;
import java.util.Collection;
import java.util.Collections;
import java.util.Map;

/**
 * A provider of a DI module of a given kind. Central to Bootique module auto-loading and metadata discovery.
 * Bootique modules normally supply "META-INF/services/io.bootique.BQModuleProvider" file packaged in the .jar containing
 * the name of the provider.
 *
 * @see Bootique#autoLoadModules()
 * @since 0.8
 */
public interface BQModuleProvider {

    /**
     * Returns a Guice module specific to this provider.
     *
     * @return an instance of a Guice Module specific to this provider.
     */
    Module module();

    /**
     * Returns a new instance of {@link io.bootique.BQModule.Builder} initialized with module for this provider.
     * Subclasses can invoke extra builder methods to provide metadata, etc.
     *
     * @return a new instance of {@link BQModule} specific to this provider.
     * @since 0.21
     */
    default BQModule.Builder moduleBuilder() {
        return BQModule
                .builder(module())
                .id(id())
                .overrides(overrides())
                .providerName(name())
                .configs(configs());
    }

    /**
     * A potentially empty map of configuration types supported by this module, keyed by default configuration
     * prefix.
     *
     * @return a potentially empty map of configuration types supported by this module, keyed by default configuration
     * prefix.
     * @since 0.21
     */
    default Map<String, Type> configs() {
        return Collections.emptyMap();
    }

    /**
     * Returns a potentially empty Collection with the types of the module
     * overridden by this Module.
     *
     * @return a potentially empty collection of modules overridden by the
     * Module created by this provider.
     * @since 0.10
     */
    default Collection<Class<? extends Module>> overrides() {
        return Collections.emptyList();
    }

    /**
     * Returns a human readable name of the provider.
     *
     * @return a human readable name of the provider. Equals to the "simple" class name by default.
     * @since 0.12
     */
    default String name() {
        return getClass().getSimpleName();
    }

    /**
     * Identifier of module.
     *
     * Each module in bootique loads through {@link BQModuleProvider}.
     * User can define {@link BQModuleProvider} explicitly,
     * or it will be auto generated by Bootique.
     *
     * Explicit {@link BQModuleProvider} should provide valid {@link BQModuleId}
     * usually instance of {@link ClassBQModuleId}.
     *
     * Examples of explicit {@link BQModuleProvider}s:
     *
     * 1. Auto-loaded {@link BQModuleProvider}s;
     * 2. {@link BQModuleProvider} loaded through dependency graph;
     * 3. {@link BQModuleProvider} passed using bootique builder.
     *
     * Implicit {@link BQModuleProvider} created by bootique from provided modules.
     *
     * Examples of implicit {@link BQModuleProvider}s:
     *
     * 1. {@link Bootique#module(Module)} - {@link BQModuleId} will be generated based on
     * module reference equality, i.e. {@link InstanceBQModuleId} will be used.
     * 2. {@link Bootique#module(Class)} - Id should be generated based on module class equality.
     *
     * @return id of module.
     * @since 0.25
     */
    BQModuleId id();

    /**
     * Returns a collection of providers of modules on which this provider's module depends. Concrete providers can
     * optionally define dependencies on other modules through this method. This allows to load app modules with
     * dependencies without relying on auto-loading.
     *
     * @return collection of bootique module providers on which the current module depends.
     * @since 0.25
     */
    default Collection<Class<? extends BQModuleProvider>> dependencies() {
        return Collections.emptyList();
    }
}
