// Licensed to ObjectStyle LLC under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ObjectStyle LLC licenses
// this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

== Injection

We've mentioned that Bootique is built on own Bootique dependency injection (DI) container.
We'll talk more about injection elsewhere. Here we'll provide a simple example.
Our simple app already has a number of objects and services working behind the scenes that can be injected.
One of them is command-line arguments that were provided to the app on startup.
Let's extend our resource to include those arguments in the output:

[source,java]
----
include::../../../../test/java/com/foo/HelloResource.java[tags=HelloInjectResource]
----

As you see, we declared a variable of type `String[]` and annotated it with `@jakarta.inject.Inject` and `@io.bootique.annotation.Args`.
`@Inject` ensures that the value is initialized via injection,
and `@Args` tells Bootique which one of possibly many String[] instances from the DI container we are expecting here.

Now you can restart the app and refresh http://localhost:10001/hello[http://localhost:10001/hello] in the browser.
The new output will be "Hello, world! The app was started with the following arguments: `--server --config=myconfig.yml`".

Next let's discuss how to build and run the app outside the IDE...